import React, { useState } from 'react';
import PinInput from 'react-pin-input';
import { useLocation } from 'react-router-dom';  // Import useLocation to get OTP from the previous page
import LoginBot from "../../assets/loginbot.png";
import styles from "../loginComponents/AuthEmail.module.css";

const AuthEmail = () => {
  const [pin, setPin] = useState('');
  const [errorMessage, setErrorMessage] = useState('');  // For showing an error message if OTP doesn't match
  const location = useLocation(); // Get the passed OTP from the previous page
  const otp = location.state?.otp || ''; // Retrieve the OTP from the passed state (if available)
  
  const handleSubmit = (e) => {
    e.preventDefault();

    // Check if entered PIN matches the OTP
    if (pin === otp) {
      console.log('Entered PIN:', pin);
      console.log('OTP matched successfully!');
      // Perform actions like redirecting to the dashboard or next page
    } else {
      console.log('OTP did not match!');
      setErrorMessage('The entered code is incorrect. Please try again.');
    }
  };

  return (
    <div className={styles.container}>
      <div className={styles.authBox}>
        <div className={styles.leftSide}>
          <div className={styles.authContent}>
            <img src={LoginBot} alt="Auth Bot" className={styles.authBot} />
            <h1>Two Factor Authentication</h1>
          </div>
        </div>
        <div className={styles.rightSide}>
          <div className={styles.authForm}>
            <h2>Email 2F Authenticator</h2>
            <p>
              Please check your email inbox for the verification code. Once received, enter the code in the field below to continue.
            </p>
           
            <form onSubmit={handleSubmit}>
              <label htmlFor="authCode">Enter the 6-digit authentication code generated by your app</label>
              <PinInput
                length={6}
                focus
                type="numeric"
                inputMode="number"
                onChange={(value) => setPin(value)}
                className={styles.pinInput}
                inputStyle={{ borderColor: '#ff9d52', borderRadius: '8px', backgroundColor: '#1e1e1e', color: '#fff' }}
                inputFocusStyle={{ borderColor: '#ff632d' }}
              />
              <button type="submit" className={styles.submitButton}>Submit</button>
              {errorMessage && <p style={{ color: 'red' }}>{errorMessage}</p>}  {/* Show error message if OTP doesn't match */}
              <a href="#">Resend</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AuthEmail;
