import axios from "axios"; // For making HTTP requests
import React, { useState } from "react";
import PinInput from "react-pin-input";
import LoginBot from "../../assets/loginbot.png";
import styles from "./MultiFactorGoogle.module.css";
import { useNavigate } from "react-router-dom"; // Import useNavigate

const MultiFactorGoogle = () => {
  const [pin, setPin] = useState("");
  const [resultMessage, setResultMessage] = useState("");
  const navigate = useNavigate(); // Initialize useNavigate

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const response = await axios.post(
        // "https://sih24-node-backend.onrender.com/verify",
        "http://localhost:3000/verify",
        {
          token: pin,
        }
      );
      if (response.data.verified) {
        setResultMessage("Code verified successfully!");
        navigate("/chatbot"); // Pass both email and OTP
      } else {
        setResultMessage("Invalid code! Please try again.");
      }
    } catch (error) {
      console.error("Error verifying code:", error);
      setResultMessage("An error occurred during verification.");
    }
  };

  return (
    <div className={styles.container}>
      <div className={styles.authBox}>
        <div className={styles.leftSide}>
          <div className={styles.authContent}>
            <img src={LoginBot} alt="Auth Bot" className={styles.authBot} />
            <h1>Two Factor Authentication</h1>
          </div>
        </div>
        <div className={styles.rightSide}>
          <div className={styles.authForm}>
            <h2>Google OAuth</h2>
            <p>
              Open your Google Authenticator app to retrieve the verification
              code.
            </p>
            <form onSubmit={handleSubmit}>
              <label htmlFor="authCode">
                Enter the 6-digit authentication code generated by your app
              </label>
              <PinInput
                length={6}
                focus
                type="numeric"
                inputMode="number"
                onChange={(value) => setPin(value)}
                className={styles.pinInput}
                inputStyle={{
                  borderColor: "#ff9d52",
                  borderRadius: "8px",
                  backgroundColor: "#1e1e1e",
                  color: "#fff",
                }}
                inputFocusStyle={{ borderColor: "#ff632d" }}
              />
              <button type="submit" className={styles.submitButton}>
                Submit
              </button>
            </form>
            {resultMessage && <p>{resultMessage}</p>}
          </div>
        </div>
      </div>
    </div>
  );
};

export default MultiFactorGoogle;
